### ISSUE TITLE
error TS2344

### ISSUE THREAD

**Issue by tzi21** [martin-nderitu/inventory-manager-backend#1]
Hello and thanks for your repository,
when i try to run the back end i get these errors (TS2344)
Do you know any way i can solve this problem?
![Screenshot from 2022-05-27 16-24-40](https://user-images.githubusercontent.com/22482238/170708141-29e63fcc-879a-4eb0-943c-d419f1674fd1.png)

**Comment by martin-nderitu** [comment]
Downgrade your sequelize version by running `npm install sequelize@6.8.0` or `yarn add sequelize@6.8.0`

**Comment by martin-nderitu** [comment]
I have updated the code to work with the new sequelize type definitions. The code should work now.

**Comment by tzi21** [comment]
Thanks a lot, for your quick response!!!
Im using mariadb, everything runs smoothly, but it does not display anything that is in the table except from suppliers. 
(for example, it creates a new category that i can see it via terminal, but when running the page it gets me the error DB error getting category)
![Screenshot from 2022-05-30 13-22-12](https://user-images.githubusercontent.com/22482238/170972519-32ea46db-9027-4ee7-be2b-0722734b5b5a.png)

**Comment by martin-nderitu** [comment]
Thanks for the feedback. The bug has now been fixed. I also made some little changes to the front-end code as well. Kindly let me know in case you face any other problems
