### ISSUE TITLE
in continuing of the first issue

### ISSUE THREAD

**Issue by tzi21** [martin-nderitu/inventory-manager-backend#2]
I have updated the code to work with the new sequelize type definitions. The code should work now.

_Originally posted by @martin-nderitu in https://github.com/martin-nderitu/inventory-manager-backend/issues/1#issuecomment-1140223716_

Thanks a lot, for your quick response!!!
Im using mariadb, everything runs smoothly, but it does not display anything that is in the table except from suppliers.
(for example, it creates a new category that i can see it via terminal, but when running the page it gets me the error DB error getting categories
![Screenshot from 2022-05-30 13-22-12](https://user-images.githubusercontent.com/22482238/170994114-8da352f7-fbf9-4999-b8c1-e7fa194416b5.png)
)

**Comment by martin-nderitu** [comment]
Could you please end a screenshot?

**Comment by martin-nderitu** [comment]
Clone the repo once more and run the code. The bug has been fixed

**Comment by tzi21** [comment]
You are amazing, thanks a lot for responding again, i cloned the repos for the front and back again, and now i cant create a new category. Im getting this error, and the error when displaying the categories, persists.
Suppliers still working smoothly, creating and displaying!
![Screenshot from 2022-05-30 15-55-18](https://user-images.githubusercontent.com/22482238/170996943-fbf90f03-0b69-44d1-a863-aaa6af95327a.png)

![Screenshot from 2022-05-30 15-57-36](https://user-images.githubusercontent.com/22482238/170997197-469e40c9-72e7-4e1e-b03b-7d6a23065eb5.png)

**Comment by martin-nderitu** [comment]
I cannot seem to reproduce your issue. Have you provided the correct database credentials in your .env file?

**Comment by martin-nderitu** [comment]
Try deleting the database and creating it again so that the changes I made to the categories table be reflected. Let me know if it works.

**Comment by tzi21** [comment]
I dropped the database, and created a new one, now it seems i cannot create a new supplier since im getting errors when typing the data, the .env file is correct
![Screenshot from 2022-05-30 16-09-01](https://user-images.githubusercontent.com/22482238/170999067-4631052a-078a-4c6f-8b07-7aab7e36dc23.png)
![Screenshot from 2022-05-30 16-08-57](https://user-images.githubusercontent.com/22482238/170999080-f42e3154-29ce-44dc-b414-210b5d5408dd.png)

**Comment by martin-nderitu** [comment]
Press Ctrl + C on terminal to close the app. Drop database, create database again and then run `yarn start`

**Comment by tzi21** [comment]
After a clean uninstall, drop etc it seems to work perfectly, thenx a lot for your help. 
I want to see if i can recreate your concept in a decentalized way. If i proceed successfully i will most certainly forward what i made to you. Thanks again my friend!

**Comment by martin-nderitu** [comment]
No problem
